In [2]:
import numpy as np 


In [3]:
arr = np.arange(1,10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
arr[2]

np.int64(3)

In [6]:
arr[0:4]

array([1, 2, 3, 4])

In [10]:
arr= np.arange(1,10).reshape(3,3)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
arr[0,0]

np.int64(1)

In [14]:
arr[0:3,1:3]

array([[2, 3],
       [5, 6],
       [8, 9]])

In [18]:
index = arr%2==0
index

array([ True,  True,  True,  True])

In [19]:
arr= arr[index]
arr

array([2, 4, 6, 8])